# Generated by Django 3.2.8 on 2021-11-20 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='users/user_default_img.png', force_format='JPEG', keep_meta=True, null=True, quality=99, size=[320, 320], upload_to=users.models.user_directory_path)),
                ('bio', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('not specified', 'Rather not say')], max_length=13, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
