# Generated by Django 3.2.8 on 2021-11-20 11:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shoes_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('shoe_size', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Boots', 'Boots'), ('Sneakers', 'Sneakers'), ('Cooperate', 'Cooperate'), ('Men', 'Men'), ('Women', 'Women')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=6)),
                ('posted_at', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=50)),
                ('about_shop', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=30)),
                ('facebook', models.CharField(blank=True, max_length=30)),
                ('twitter', models.CharField(blank=True, max_length=30)),
                ('image1', models.ImageField(default='', upload_to=shoes_app.models.shoe_directory_path)),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to=shoes_app.models.shoe_directory_path)),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to=shoes_app.models.shoe_directory_path)),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to=shoes_app.models.shoe_directory_path)),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to=shoes_app.models.shoe_directory_path)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
