# Generated by Django 3.2.8 on 2021-11-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('Boots', 'Boots'), ('Sneakers', 'Sneakers'), ('Sports', 'Sports'), ('Men', 'Men'), ('Women', 'Women')], max_length=10),
        ),
    ]
