# Generated by Django 3.2.8 on 2021-11-26 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_app', '0002_alter_shoe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='time_posted',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
